/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Appointment;
import javax.swing.JOptionPane;

/**
 *
 * @author sasch
 */
public class AppointmentDlg extends javax.swing.JDialog {

    /**
     * Creates new form AppointmentDlg
     */
    private Appointment newAppointment;
    Appointment a;

    public Appointment getNewAppointment() {
        return newAppointment;
    }
    
    public AppointmentDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public AppointmentDlg(java.awt.Frame parent, boolean modal,Appointment a) {
        super(parent, modal);
        initComponents();
        this.a=a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        btApply = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        jLabel1.setText("Tag");
        jPanel1.add(jLabel1);
        jPanel1.add(tfTag);

        jLabel2.setText("Monat");
        jPanel1.add(jLabel2);
        jPanel1.add(tfMonat);

        jLabel3.setText("Jahr");
        jPanel1.add(jLabel3);
        jPanel1.add(tfJahr);

        jLabel4.setText("Stunde");
        jPanel1.add(jLabel4);
        jPanel1.add(tfStunde);

        jLabel5.setText("Minute");
        jPanel1.add(jLabel5);
        jPanel1.add(tfMinute);

        jLabel6.setText("Text");
        jPanel1.add(jLabel6);
        jPanel1.add(tfText);

        btApply.setText("übernehmen");
        btApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onApply(evt);
            }
        });
        jPanel1.add(btApply);

        btCancel.setText("abbrechen");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        jPanel1.add(btCancel);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onApply(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onApply
        Appointment newAp;
        try {
            String text,stunde, minute, tag, monat, jahr;

            stunde =tfStunde.getText();
            minute=tfMinute.getText();
            tag =tfTag.getText();
            monat =tfMonat.getText();
            jahr =tfJahr.getText();
            text = tfText.getText();

            newAp = new Appointment(tag,monat,jahr,stunde,minute,text);

            //alles okay = dlg schließen
            dispose();
            //todo: Kaskadieren der Catches!!!
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage());
        }
    }//GEN-LAST:event_onApply

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApply;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
