/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.AppointmentBIN;
import BL.AppointmentModell;

/**
 *
 * @author sasch
 */
public class AppointmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentGUI
     */
    AppointmentModell apmd;
    AppointmentBIN apbin;
    //das parsen in Appointment funktioniert nicht, trotz vieler versuche diesen Fehler zu beheben!!!!!!!!!!!!!!!!!!!
    public AppointmentGUI() {
        initComponents();
        apmd=new AppointmentModell();
        liAusgabe.setModel(apmd);
        try {
            apmd=new AppointmentModell(apbin.readBin());
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmMenue = new javax.swing.JPopupMenu();
        miAdd = new javax.swing.JMenuItem();
        miRemove = new javax.swing.JMenuItem();
        miEdit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        liAusgabe = new javax.swing.JList();

        miAdd.setText("hinzufügen");
        miAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdd(evt);
            }
        });
        pmMenue.add(miAdd);

        miRemove.setText("löschen");
        miRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onRemove(evt);
            }
        });
        pmMenue.add(miRemove);

        miEdit.setText("ändern");
        miEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEdit(evt);
            }
        });
        pmMenue.add(miEdit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Termine"));
        jPanel1.setLayout(new java.awt.GridLayout());

        liAusgabe.setComponentPopupMenu(pmMenue);
        jScrollPane2.setViewportView(liAusgabe);

        jPanel1.add(jScrollPane2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdd
      AppointmentDlg dlg=new AppointmentDlg(this,true);
      dlg.setVisible(true);
      apmd.add(dlg.getNewAppointment());
    }//GEN-LAST:event_onAdd

    private void onRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onRemove
        apmd.remove(liAusgabe.getSelectedIndex());
    }//GEN-LAST:event_onRemove

    private void onEdit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEdit
        AppointmentDlg dlg=new AppointmentDlg(this,true);
        dlg.setVisible(true);
        apmd.set(dlg.getNewAppointment(),liAusgabe.getSelectedIndex());
    }//GEN-LAST:event_onEdit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList liAusgabe;
    private javax.swing.JMenuItem miAdd;
    private javax.swing.JMenuItem miEdit;
    private javax.swing.JMenuItem miRemove;
    private javax.swing.JPopupMenu pmMenue;
    // End of variables declaration//GEN-END:variables
}
